规则:
  dimension_definitions:
    技能:
      description: 指令执行、多应用协同操作能力.
      优质标签:
        - 技能_1. 复杂指令完成度高
    文本生成:
      description: 根据提示自动生成连贯文本.
      优质标签:
        - 生文_1. 内容质量_观点独到
        - 生文_2. 逻辑结构_论证有层次
        - 生文_3. 语言表达_修辞丰富
        - 生文_4. 实用价值_专业深入
        - 生文_5. 阅读体验_情节感人
      注意事项:
        - 扩写在原文的文本内容基础上添加，扩充了一些细节或情节，不可以修改原有内容的意思；
        - 续写是在原文的内容之后继续往下写，不改变原文的内容.
    知识问答:
      description: 知识问答主要是指与各行业知识相关的问答，要求在处理涉及健康、法律等敏感信息时，要给出免责声明.
      优质标签:
        - 问答_1. 专业有深度
        - 问答_2. 实用价值高
        - 问答_3. 创新观点
        - 问答_4. 逻辑层次佳
      注意事项:
        - 价值观类：当用户的问题中有关vivo的负面评价：回答内容中要诚恳致歉+反馈途径；有关vivo竞品的负面评价：要客观评价并中立立场
          当用户对部分非vivo官方消息与vivo未来规划存在好奇与探索欲时，回答的理想格式：回答了用户的问题，并且有关vivo的提问要给出结论+引导；有关竞品的提问：要回答了用户的问题，并给出结论+推测+引导
        - 答案显性（答案在首行或文中加粗）；最好进行适当的知识扩展，例如解释相关概念、原理、原因等；目标是提升理解，而非展示模型知识量。若扩展内容过长、冗余、偏离问题核心，或涉及内容太基础（用户可能早已掌握），则应视为负面因素，影响评分。
        - 解题类答案需在开头显性显示，选择题选项要简明解释，但避免冗长阐述及总结性长句语言。
        - 用户体验原则:无法一眼获取到结论，信息不易定位，主要问题标注："7格式及呈现不佳_1.界面呈现不佳";2、格式繁杂，层级混乱，或者是缺少相应的格式，主要问题标注"7格式及呈现不佳_2.文字格式不佳"。
        - 简洁优先原则：用户不爱阅读且没有耐心，回答必须简洁明了，不要过分扩展相关知识，否则主要问题标注"4.冗长_2. 扩展过多"或"4.冗长_3. 无关内容过多"，对同一要点或含义重复表述，尤其是首尾重复，主要问题标注"4冗长_3. 内容重复"。
        - 错误鉴别原则：回答中存在实体错误、关系错误、信息缺失、夸大主张、信息过时、无法验证、用户意图误解、检索误读等错误，仔细鉴别并在标注理由中阐述错误原因。
    聊天:
      description: 模拟人类进行轻松随意对话，注重情绪表达和拟人化.
      优质标签:
        - 闲聊_1. 拟人度高
        - 闲聊_2. 智能懂我
        - 闲聊_3. 有趣好聊
        - 闲聊_4. 温度贴心
      注意事项:
        - 期望模型的回答更口语化、拟人、自然，则更能贴近真实用户喜好；要求回答应尽量简洁，避免冗长和复杂的表达。并且能够顺畅地引导后续对话；
        - 大模型回答的信息量更多，但不一定代表更好，如果信息全面但风格僵硬、AI感强，用户体验差，要标注出来;
        - 如果用户的问题不礼貌，则要求大模型可以委婉拒绝或者劝导或者直接回答，只要内容不具备攻击性即可。

  对比:
    - 举例类：举出成语、单词、示例等例子并给出解释胜于仅给出例子
    - 翻译类：翻译多种词性并给出示例>翻译多种词性>存在例句>翻译一种词性
    - 有外部多媒体资源最好，但是需与主旨相关；如果一方有外部多媒体资源（相关图片、视频、跳转链接），则没有的一方标注富媒体资源少，双方都没有时，不对这方面进行标注
    - 解题类答案需在开头显性显示，选择题选项要简明解释，但避免冗长阐述及总结性长句语言
    - 模糊中立原则：问题语义不明确或有歧义时，模型"表达疑惑，并引导用户进一步提问"与"尝试多角度理解问题并分别作答"，均正确且竞品对比为"平"

弱智标签:
  - 1.未提供需要信息_1. 答非所问
  - 1.未提供需要信息_2. 意图错误
  - 1.未提供需要信息_3. 不合理拒答
  - 1.未提供需要信息_4. 执行异常或超时
  - 1.未提供需要信息_5. 其他
  - 2.内容质量差_1. 常识缺乏
  - 2.内容质量差_2. 逻辑混乱
  - 2.内容质量差_3. 字数及序号指代错误
  - 2.内容质量差_4. 文字游戏错误
  - 2.内容质量差_5. 冗余重复过多
  - 2.内容质量差_6. 乱码与脏数据
  - 2.内容质量差_7. 人称指代错误
  - 2.内容质量差_8. 其他
  - 3.多轮效果不佳_1. 多轮记忆错误
  - 3.多轮效果不佳_2. 多轮逻辑错误
  - 3.多轮效果不佳_3. 多轮指代错误
  - 4.其他_1.其他

单个大模型主要问题:
  - 1未提供需要信息_1.回答不全：未回答用户问题中的核心问题，或遗漏关键信息
  - 1未提供需要信息_2.答非所问：回答内容与用户问题无关
  - 1未提供需要信息_3.意图错误：误解用户意图，回答方向错误
  - 1未提供需要信息_4.执行异常：回答内容明显不符合指令要求，或出现错误
  - 1未提供需要信息_5.其他：指未提供用户需要的信息，但不是上述原因引起的
  - 2内容质量差_1.正确性不足：回答内容存在事实性错误、逻辑错误、计算错误等
  - 2内容质量差_2.准确性不足：回答内容模糊不清、模棱两可，或存在歧义
  - 2内容质量差_3.要点不全面：要点指用户问题中的关键信息或必须回答的问题点，回答不全面
  - 2内容质量差_4.实用性不佳：回答模糊、空洞等，未提供实质帮助
  - 2内容质量差_5.时效性不足：回答内容过时，与当前实际情况不符
  - 2内容质量差_6.可靠性不足：回答内容缺乏依据，或来源不可靠
  - 2内容质量差_7.其他：指内容质量方面存在问题，但不属于上面的原因
  - 3逻辑与结构不佳_1.逻辑混乱：回答内容逻辑不清，前后矛盾，或缺乏连贯性
  - 3逻辑与结构不佳_2.结构不清晰：回答内容组织混乱，层次不分明，或缺乏清晰的结构
  - 3逻辑与结构不佳_3.其他：指逻辑与结构方面存在问题，但不属于上面的原因
  - 4冗长_1.篇幅过长：回答的篇幅过长，增加了文字没有增加信息含量
  - 4冗长_2.拓展过多：过度延伸话题，添加过多与核心问题关系不大的背景知识、衍生内容等
  - 4冗长_3.无关内容过多：回答中包含过多与问题无关的内容
  - 4冗长_4.内容重复：对同一要点或含义重复表述，尤其是首尾重复
  - 4冗长_5.其他：回答内容不够简洁，但不是上述原因引起的
  - 5简略_1.篇幅过短：在答案正确基础上，内容过短，且有负面感受，信息含量过少
  - 5简略_2.拓展过少：仅给出结论或简单答案，没有对相关概念、原理、原因等进行适当解释
  - 5简略_3.表达过于精简：多个部分缺乏过渡衔接，表达过于精简
  - 5简略_4.内容多样性不足：回答出问题内容，但表达角度较为单一，缺乏多样性
  - 5简略_5.其他：回答内容简略，但不是上述原因引起的
  - 6语言表达不佳_1.AI感强：过度书面化表达或过于模板化
  - 6语言表达不佳_2.风格不一致：口语化问题回复过于书面化
  - 6语言表达不佳_3.无免责声明：在涉及医疗、法律、金融等涉及安全的内容时，无免责声明
  - 6语言表达不佳_4.有攻击性：回复不礼貌，带有攻击性
  - 6语言表达不佳_5.无引导询问：在问题表意不清时、需要引导时没有进一步询问
  - 6语言表达不佳_6.其他：指大模型的回答在语言表达方面有问题，但不是上述原因引起的
  - 7格式及呈现不佳_1.界面呈现不佳：答案不显性，未突出重点，可读性差，无法直观获取答案
  - 7格式及呈现不佳_2.文字格式不佳：针对文字本身的格式不规范，文字排版不佳，可读性差；或表格，markdown等特殊格式有问题
  - 7格式及呈现不佳_3.其他：指大模型回答的格式不佳，可读性差，回答要点未突出，但不是上述原因引起的
  - 8内容要素不佳_1.组织内容形式少：指的是对方回答中有辅助提供答案指令的形式，如表格或思维导图等，但是本模型没有
  - 8内容要素不佳_2.富媒体资源少：指对方回答中有对内容有效果增益的图片、视频等多媒体资源
  - 8内容要素不佳_3.无用资源过多：存在富媒体资源，但属于无关广告或相关性差
  - 12弱智：模型犯低级错误，不能容忍；输出出现逻辑不通、不合常理的低级错误
  - 13无问题：若不存在上述所有问题，大模型的回答没有存在任何问题，可选此问题标签
  - 14优质：大模型的回答超级超级专业有深度并且实用价值高并且逻辑层次佳，逻辑严密，并且简洁易懂

SBS主要问题:
  - 2内容质量差_3.要点不全面：要点指用户问题中的关键信息或必须回答的问题点，与对方相比，对这些要点回答的不全面
  - 2内容质量差_4.实用性不佳：指与对方相比，回答模糊、空洞等，未提供实质帮助，不如对方实用性好
  - 2内容质量差_7.其他：指与对方相比，回答内容质量方面存在问题，但是不属于上面的原因
  - 4冗长_1.篇幅过长：指与对方相比，本大模型回答的篇幅有点过长，增加了文字没有增加信息含量
  - 4冗长_2.拓展过多：过度延伸话题，添加过多与核心问题关系不大的背景知识、衍生内容等，偏离用户提问的核心
  - 4冗长_5.其他：回答内容不够简洁，但是不是上述原因引起的
  - 5简略_1.篇幅过短：与对方相比，内容过短，且有负面感受，信息含量过少
  - 5简略_2.拓展过少：仅给出结论或简单答案，没有对相关概念、原理、原因等进行适当解释
  - 5简略_3.表达过于精简：多个部分缺乏过渡衔接，表达过于精简
  - 5简略_4.内容多样性不足：回答出问题内容，但表达角度较为单一，缺乏多样性
  - 5简略_5.其他：回答内容简略，但是不是上述原因引起的
  - 7格式及呈现不佳_1.界面呈现不佳：答案不显性，未突出重点，可读性差，无法直观获取答案
  - 7格式及呈现不佳_2.文字格式不佳：针对文字本身的格式不规范，文字排版不佳，可读性差；或表格，markdown等特殊格式有问题
  - 7格式及呈现不佳_3.其他：指大模型回答的格式不佳，可读性差，回答要点未突出，但不是上述原因引起的
  - 8内容要素不佳_1.组织内容形式少：指的是对方回答中有辅助提供答案指令的形式，如表格或思维导图等，但是本模型没有
  - 8内容要素不佳_2.富媒体资源少：指对方回答中有对内容有效果增益的图片、视频等多媒体资源
  - 8内容要素不佳_3.无用资源过多：存在富媒体资源，但属于无关广告或相关性差